spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pet-funeral-db.cpuaeay8sypv.ap-northeast-2.rds.amazonaws.com:3306/pet-funeral-db?serverTimezone=Asia/Seoul
    username: admin
    password: ${DB_PASSWORD}